name: Lahme
favicon: null
layout_spectrum: 0.043564581545069814
typography_spectrum: 0.042683606734499335
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8824739709962159
  lightness: 0.23176538245752454
  saturation: 0.022721485234797
  rhythmicContrast: 0.2333481223322451
purpose: []
